import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import clinicsRouter from "./clinics.js";
import patientsRouter from "./patients.js";
import proceduresRouter from "./procedures.js";
import appointmentsRouter from "./appointments.js";
import schedulesRouter from "./schedules.js";
import medicalRecordsRouter from "./medical-records.js";
import financialRouter from "./financial.js";
import reportsRouter from "./reports.js";
import dashboardRouter from "./dashboard.js";
import usersRouter from "./users.js";
import storageRouter from "./storage.js";
import blockedSlotsRouter from "./blocked-slots.js";
import publicRouter from "./public.js";
import subscriptionsRouter from "./subscriptions.js";
import auditLogRouter from "./audit-log.js";
import packagesRouter from "./packages.js";
import patientPackagesRouter from "./patient-packages.js";
import treatmentPlanProceduresRouter from "./treatment-plan-procedures.js";
import patientJourneyRouter from "./patient-journey.js";
import recurringExpensesRouter from "./recurring-expenses.js";
import saasPlanRouter from "./saas-plans.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/public", publicRouter);
router.use("/auth", authRouter);
router.use("/clinics", clinicsRouter);
router.use("/users", usersRouter);
router.use("/patients", patientsRouter);
router.use("/patients/:patientId", medicalRecordsRouter);
router.use("/patients/:patientId", patientJourneyRouter);
router.use("/patients/:patientId/packages", patientPackagesRouter);
router.use("/procedures", proceduresRouter);
router.use("/packages", packagesRouter);
router.use("/treatment-plans/:planId/procedures", treatmentPlanProceduresRouter);
router.use("/appointments", appointmentsRouter);
router.use("/schedules", schedulesRouter);
router.use("/blocked-slots", blockedSlotsRouter);
router.use("/financial", financialRouter);
router.use("/subscriptions", subscriptionsRouter);
router.use("/reports", reportsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/storage", storageRouter);
router.use("/audit-log", auditLogRouter);
router.use("/recurring-expenses", recurringExpensesRouter);
router.use("/", saasPlanRouter);

export default router;
